server {
  listen 8080;
  server_name _;
  root /usr/share/nginx/html;
  client_max_body_size 12m;
  location /api/ {
    proxy_pass http://backend:5000;
    proxy_read_timeout 90s;
    proxy_set_header Host $host;
  }
  location / { try_files $uri $uri/ /index.html; }
  add_header X-Content-Type-Options nosniff;
}
